server:
  port: 8001

logging:
  level:
    edu.xidian.springcloud.controller: debug
    
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: edu.xidian.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
  
  
spring:
  application:
    name: microservicecloud-dept
  datasource: 
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true  
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500